apiVersion: v1
kind: Service
metadata:
  name: kt-svc
  labels:
    app.kubernetes.io/instance: kong-new-app
spec:
  type: NodePort
  selector:
    app: kt
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kt-deploy
  labels:
    app.kubernetes.io/instance: kong-new-app
spec:
  replicas: 10
  selector:
    matchLabels:
      app: kt
  template:
    metadata:
      labels:
        app: kt
    spec:
      containers:
        - name: kt-container
          image: sjhong1994/k8s-lab:1.0
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: kakao-svc
  labels:
    app.kubernetes.io/instance: kong-new-app
spec:
  type: NodePort
  selector:
    app: kakao
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kakao-deploy
  labels:
    app.kubernetes.io/instance: kaong-new-app
spec:
  replicas: 10
  selector:
    matchLabels:
      app: kakao
  template:
    metadata:
      labels:
        app: kakao
    spec:
      containers:
        - name: kakao-container
          image: sjhong1994/k8s-lab:1.0
          ports:
            - containerPort: 80
