apiVersion: v1
kind: ConfigMap
metadata:
  name: nks-metrics-exporter
data:
  baseurl: https://cw.apigw.ntruss.com
  basepath: /cw_collector/real/data
  dmn_cd: PUB
  prodkey: "526115048926613504"
  nrn: nrn:PUB:VPCKubernetesService:KR:2633384:Cluster/bf53abe3-186c-4c32-adca-3e1adc39c586 #Resource Manager에 기재된 K8s Cluster nrn 번호
  accesskey: 92CFF3BFB5C978367F9D
  secretkey: 40E660C65D74E89D2A97BE7B7F291DFC91C6496D
  ignore_namespaces: kube-system  #특정 네임스페이스내 pod의 자원사용량을 집계하지 않으려면, 해당 필드에 네임스페이스 이름 입력. 복수의 값 입력 시 , 콤마로 분리하여 기술 가능
